"""empty message

Revision ID: 5060f3149860
Revises: None
Create Date: 2016-05-28 17:16:50.181210

"""

# revision identifiers, used by Alembic.
revision = '5060f3149860'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pages',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('PageName', mysql.TEXT(), nullable=True),
    sa.Column('PageContent', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('Username', mysql.TEXT(), nullable=True),
    sa.Column('Password', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PageHistory',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('content_added', mysql.TEXT(), nullable=True),
    sa.Column('content_removed', mysql.TEXT(), nullable=True),
    sa.Column('currentcontent', mysql.TEXT(), nullable=True),
    sa.Column('dateofchange', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['Pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PageHistory')
    op.drop_table('Users')
    op.drop_table('Pages')
    ### end Alembic commands ###
