"""empty message

Revision ID: 517ac2f2cee
Revises: None
Create Date: 2016-01-11 19:12:10.090113

"""

# revision identifiers, used by Alembic.
revision = '517ac2f2cee'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pages',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('PageName', mysql.TEXT(), nullable=True),
    sa.Column('PageContent', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('Username', mysql.TEXT(), nullable=True),
    sa.Column('Password', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Pages')
    ### end Alembic commands ###
