"""empty message

Revision ID: e85d49d37684
Revises: 517ac2f2cee
Create Date: 2016-02-06 21:11:50.240369

"""

# revision identifiers, used by Alembic.
revision = 'e85d49d37684'
down_revision = '517ac2f2cee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PageHistory',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('content_added', mysql.TEXT(), nullable=True),
    sa.Column('content_removed', mysql.TEXT(), nullable=True),
    sa.Column('currentcontent', mysql.TEXT(), nullable=True),
    sa.Column('dateofchange', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['Pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PageHistory')
    ### end Alembic commands ###
